<a href="https://colab.research.google.com/github/nedokormysh/Ai_edu_math/blob/week_3_complex_det/homework_3_NumPy_Berezutskiy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Домашнее задание. Библиотека NumPy

### Общая информация

### Формат сдачи

Задание выполняем в Google Colab. В качестве ответа отправляем ссылку на ноутбук в Google Classroom

### О задании

В данном домашнем задании вы попрактикуетесь в работе с библиотекой numpy!

In [27]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

### Задание 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :)

In [28]:
def result_mark(weights: np.array, marks: np.array) -> float:
    '''
    Функция, возвращающая взвешенную сумму оценок
    '''
    return sum(weights * marks)

In [29]:
weights = np.array([0.35, 0.4, 0.15, 0.1])
marks = np.array([6, 9, 8, 7])
result_mark(weights, marks)

7.6

*Не знаю можно ли писать как np.array, но по-другому, если импортировать алиасом - не работает.*

### Задание 2

Напишите функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [30]:
def change_array(array: np.array, number: float) -> np.array:
    '''
    Функция замены каждого третьего числа массива на заданное значение
    '''
    array[::3] = number
    return array

In [31]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

### Задание 3

Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])` (_**важно: не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть `.ndim` от него равно 1)!**_).

In [32]:
def find_close(array1: np.array, array2: np.array, precision: float) -> np.array:
    '''
    Функция нахождения индексов элементов, где числа двух заданных массивов
    не отличаются на определённую величину
    '''
    return np.where(abs(array1 - array2) <= precision)[0]

In [33]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)

array([0, 1, 3, 6])

In [34]:
find_close(array1, array2, precision).ndim

1

### Задание 4

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
то ответом будет матрица
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [35]:
def block_matrix(block: np.array) -> np.array:
    '''
    Функция возвращает блочную матрицу из четырёх одинаковых заданных блоков
    '''
    return np.block([[block, block],
                     [block, block]])

In [36]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### Задание 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

In [37]:
def diag_prod(matrix: np.array) -> float:
    '''
    Функция для вычисления произведения ненулевых диагональных элементов
    '''
    return np.diag(matrix)[np.diag(matrix) != 0].prod()

In [38]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

### Задание 6

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать [нормализацию данных](https://vk.cc/8xmfQk), чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
то результатом с точностью до сотых будет матрица
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Подсказка. Учтите, что в вашей матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему._


In [39]:
def normalize_1(matrix: np.array) -> np.array:
    '''
    Функция, нормализующая входящую матрицу (по столбцам)
    '''
    matrix_ = matrix - np.mean(matrix,axis=0)
    std = np.std(matrix,axis=0)
    matrix_normed = np.divide(matrix_, std, where=(std != 0))

    return matrix_normed

In [40]:
def normalize_2(matrix):
    matrix_ = matrix - np.mean(matrix,axis=0)
    safe_std = np.std(matrix,axis=0)
    # safe_std = np.where(safe_std != 0, safe_std, 1)
    safe_std[safe_std==0] = 1
    matrix_normed = matrix_ / safe_std

    return matrix_normed

In [41]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize_1(matrix)

array([[ 0.70710678, -0.39223227,  0.46291005],
       [-1.41421356,  1.37281295,  0.9258201 ],
       [ 0.70710678, -0.98058068, -1.38873015]])

*Здесь не совсем ясно. не уверен, что что-то сделал правильно, поэтому оставил 2 версии функции. Чистое деление на ноль даёт нам inf. Std == 0, если у нас все элементы равны. Тогда мы дейсвительно получим nan. Но как правильно его обрабатывать - не знаю. Предположил, что мы хотим, считать, что тогда наше std = 1. Поэтому в колонках нормализованной матрицы получаем 0, вместо nan. Но как правильно - если честно, не знаю. Но получил этот ноль ещё и в варианте, где я накладываю условие where на np.divide*

In [42]:
matrix = np.array([[1, 4, 4200], [1, 4, 5000], [1, 4, 1000]])
normalize_1(matrix)

array([[ 0.        ,  0.        ,  0.46291005],
       [ 0.        ,  0.        ,  0.9258201 ],
       [ 0.        ,  0.        , -1.38873015]])

In [43]:
normalize_2(matrix)

array([[ 0.        ,  0.        ,  0.46291005],
       [ 0.        ,  0.        ,  0.9258201 ],
       [ 0.        ,  0.        , -1.38873015]])

### Задание 7

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

In [44]:
def antiderivative(coefs):
    '''
    Функция, вычисляющая первообразную полинома
    '''
    fav_const = -2
    return np.polyint(coefs, k=fav_const)

In [45]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([ 1.,  2.,  0.,  1., -2.])

In [46]:
p = np.polynomial.polynomial.Polynomial(np.flip(antiderivative(coefs)))
print(p)

-2.0 + 1.0·x¹ + 0.0·x² + 2.0·x³ + 1.0·x⁴


### Задание 8

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [47]:
def make_symmetric(matrix: np.array) -> np.array:
    '''
    Фунция для вовзрата симметричной матрицы
    '''
    return np.tril(matrix.T, -1) + matrix

In [48]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

### Задание 9

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [49]:
def construct_matrix(m, a, b):
    return np.zeros((5, (b + 1) - a)) + np.arange(a, b + 1)

In [50]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

array([[ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

### Задание 10

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

In [51]:
def cosine_similarity(vec1: np.array, vec2: np.array) -> float:
    '''
    Функция для вычисления косинусной близости
    '''
    return (vec1 * vec2).sum() / (np.sqrt(np.sum(vec1**2)) * np.sqrt(np.sum(vec2**2)))

In [52]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25