<a href="https://colab.research.google.com/github/nedokormysh/Ai_edu_math/blob/week_3_complex_det/HW_3_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1.
**Используя явную формулу для нахождения обратной матрицы, вычислите** $A^{-1}$,**где**

$$A =\begin{pmatrix}
1 & -2 & 1  \\
3 & -4 & 3 \\
-9 & 10 & -7
\end{pmatrix}$$

Явная форма - это через алгебраические дополнения? Во всяком случае, так предположил.

$A^{-1} = \frac{A^T_*}{|A|}$

1) Найдём определитель

$$\begin{vmatrix}
1 & -2 & 1\\
3 & -4 & 3\\
-9 & 10 & -7
\end{vmatrix} = 1 * (-4) * (-7) + (-2) * 3 * (-9)+ 1 * 3 * 10 - (-9) * (-4) * 1 - 10 * 3 * 1 - (-7) * 3 * (-2) = 28 + 54 + 30 - 36 - 30 - 42 = 4$$

2) Найдём матрицу миноров
* $$\begin{vmatrix}
-4 & 3\\
 10 & -7
\end{vmatrix} = 28 - 30 = -2$$

* $$\begin{vmatrix}
3  & 3\\
-9 & -7
\end{vmatrix} = -21 + 27 = 6$$

* $$\begin{vmatrix}
3 & -4\\
-9 & 10
\end{vmatrix} = 30 - 36 = -6$$

* $$\begin{vmatrix}
-2 & 1\\
10 & -7
\end{vmatrix} = 14 - 10 = 4$$

* $$\begin{vmatrix}
1 & 1\\
-9 & -7
\end{vmatrix} = -7 + 9 =2$$

* $$\begin{vmatrix}
1 & -2 \\
-9 & 10
\end{vmatrix} = 10 - 18 = -8$$

* $$\begin{vmatrix}
-2 & 1\\
-4 & 3\\
\end{vmatrix} = -6 + 4 = -2$$

* $$\begin{vmatrix}
1 & 1\\
3 & 3\\
\end{vmatrix} = 3 - 3 = 0$$

* $$\begin{vmatrix}
1 & -2 \\
3 & -4
\end{vmatrix} = -4 + 6 = 2$$


$$M =\begin{pmatrix}
-2 & 6 & -6  \\
4 & 2 & -8 \\
-2 & 0 & 2
\end{pmatrix}$$

3) Найдём матрицу алгебраических дополнений

$$A_* =\begin{pmatrix}
-2 & -6 & -6  \\
-4 & 2 & 8 \\
-2 & 0 & 2
\end{pmatrix}$$

4) Находим транспонированную матрицу алгебраических дополнений

$$A^T_* =\begin{pmatrix}
-2 & -4 & -2  \\
-6 & 2 & 0 \\
-6 & 8 & 2
\end{pmatrix}$$

Ответ

$$A^{-1} = \frac{1}{4} * \begin{pmatrix}
-2 & -4 & -2  \\
-6 & 2 & 0 \\
-6 & 8 & 2
\end{pmatrix} = \begin{pmatrix}
-0.5 & -1 & -0.5  \\
-1.5 & 0.5 & 0 \\
-1.5 & 2 & 0.5
\end{pmatrix}$$

In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
A = np.array([[1, -2, 1], [3, -4, 3], [-9, 10, -7]])

In [3]:
np.set_printoptions(suppress=True)

In [4]:
la.inv(A)

array([[-0.5, -1. , -0.5],
       [-1.5,  0.5,  0. ],
       [-1.5,  2. ,  0.5]])

In [5]:
detA = la.det(A)
detA

4.000000000000001

In [6]:
# import scipy.linalg

# inverse = scipy.linalg.inv(A)

# # print(inverse @ A)
# inverse

# 2.
Решите уравнение

$$\begin{pmatrix}
3 & -1 \\
5 & -2
\end{pmatrix}*X*\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix} =
\begin{pmatrix}
14 & 16 \\
9 & 10
\end{pmatrix}$$



Найдём обратные матрицы

Для матрицы $$\begin{pmatrix}
3 & -1 \\
5 & -2
\end{pmatrix}$$


$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 \\
5 & -2
\end{matrix}\right|
\begin{matrix}
1 & 0\\
0 & 1
\end{matrix}
\end{pmatrix}=\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} \\
5 & -2
\end{matrix}\right|
\begin{matrix}
\frac{1}{3} & 0\\
0 & 1
\end{matrix}
\end{pmatrix}=\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} \\
0 & -\frac{1}{3}
\end{matrix}\right|
\begin{matrix}
\frac{1}{3} & 0\\
-\frac{5}{3} & 1
\end{matrix}
\end{pmatrix}=\begin{pmatrix}
\left.\begin{matrix}
1 & -\frac{1}{3} \\
0 & 1
\end{matrix}\right|
\begin{matrix}
\frac{1}{3} & 0\\
5 & -3
\end{matrix}
\end{pmatrix}=\begin{pmatrix}
\left.\begin{matrix}
1 & 0 \\
0 & 1
\end{matrix}\right|
\begin{matrix}
2 & -1\\
5 & -3
\end{matrix}
\end{pmatrix}$$

Для матрицы $$\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}$$

1)$$\begin{vmatrix}
5 & 6\\
7 & 8
\end{vmatrix} = 40 - 42 = -2$$

2) $$-\frac{1}{2}\begin{pmatrix}
8 & -6 \\
-7 & 5
\end{pmatrix}$$

Домножим обратные матрицы на уравнение.

In [7]:
A = np.array([[3,  -1], [5, -2]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[14, 16], [9, 10]])

$$\begin{pmatrix}
2 & -1 \\
5 & -3
\end{pmatrix} * \begin{pmatrix}
14 & 16  \\
9 & 10
\end{pmatrix} = \begin{pmatrix}
28 -9 & 32 -10\\
70 - 27 & 80 - 30
\end{pmatrix} = \begin{pmatrix}
19 & 22\\
43 & 50
\end{pmatrix}$$

$$X = \begin{pmatrix}
19 & 22\\
43 & 50
\end{pmatrix} * \Big(-\frac{1}{2}\Big) \begin{pmatrix}
8 & -6\\
-7 & 5
\end{pmatrix} =
(-\frac{1}{2})\begin{pmatrix}
 152 - 154 & -114 + 110  \\
 344 - 350 & -258 + 250
\end{pmatrix} = (-\frac{1}{2})\begin{pmatrix}
-2 & -4 \\
-6 & -8
\end{pmatrix} = \begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}$$

In [8]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [9]:
A @ X @ B

array([[14, 16],
       [ 9, 10]])

# 3.
Вычислите

$$i^5 = i * (i^2)^2 = i(-1)^2 = i$$

$$i^{100} = (i^2)^{50} = (-1)^{50} = 1$$

$$i^n$$
**Не решил. Не придумал как записать**

если n делится на 2 и не делится на 4, то $i^n = -1$

если n делится на 3, то $i^n = - i$.

если n = 0 или делится на 4, то $i^n = 1$

если n нечётное, то $i^n = i$

Т.е. тут цикл $1, i, -1, -i$, но чего-то не представляю как это записать.


$$i^{4n} = 1$$
$$i^{4n+1} = i$$
$$i^{4n+2} = -1$$
$$i^{4n+3} = -i$$


#4
Вычислите

$$z = -\frac{(-1 + 5i)^2(3-4i)}{1+3i}+\frac{10+7i}{5i}=
-\frac{(-1 + 5i)(-1 + 5i)(3-4i)}{1+3i}+\frac{10+7i}{5i}=
-\frac{(1 - 5i - 5i + 25i^2)(3-4i)}{1+3i}+\frac{10+7i}{5i}=
-\frac{(-24 -10i)(3-4i)}{1+3i}+\frac{10+7i}{5i}=
-\frac{-72 + 96i - 30i + 40i^2}{1+3i}+\frac{10+7i}{5i}=
-\frac{-112 + 66i}{1+3i}+\frac{10+7i}{5i}=-\frac{(-112 + 66i)(1-3i)}{(1+3i)(1-3i)}+\frac{10+7i}{5i}=-\frac{(-112 + 336i + 66i - 198i^2)}{(1+3i)(1-3i)}+\frac{10+7i}{5i}=-\frac{(86 + 402i)}{10}+\frac{10+7i}{5i} = -8.6 - 40.2i + 2i + 1.4 = -7.2 - 42.2i $$

**Видимо не решил, но не понимаю, где ошибка. Принципиальная или арифметическая**

In [10]:
z = -(((-1 + 5j)**2) * (3-4j) / (1 + 3j)) + ((10 + 7j)/5j)
z

(-7.200000000000001-42.199999999999996j)

# 5
Какое число нужно возвести в квадрат, чтобы получить $2i$

Т.е. нам нужно найти квадратный корень из 2i

$2i = 1 + 2i -1 = 1^2 + 2*1*i + i^2 = (1 + i)^2.$

Корни $2i$ =  $± (1+i)$



Правда сам бы не решил, где-то в памяти было из университета. Возможно надо как-то через тригонометрические формулы выходить на это решение.

# 6

Решите квадратное уравнение над ℂ

$$-\frac{z^2}{i} + \frac{20z}{i-3} + (2-11i)= 0$$

Домножим на сопряжённые, чтобы избавиться от дробей

$$z^2i + \frac{20zi + 60z}{-10} + 2 - 11i$$

$$z^2i -2zi -6z + 2 - 11i$$

$$z^2i + z(-2i -6) + 2 - 11i$$


$$z_1 = \frac{-b -\sqrt{D}}{2a}$$

$$z_2 = \frac{-b +\sqrt{D}}{2a}$$

$$D = b^2-4ac$$

$$a = i$$

$$b = (-2i -6)$$

$$c = 2 - 11i$$

$$D = (-2i - 6)^2 - 4i(2 - 11i) = 24i + 32 - 8i + 44i^2 = - 12 + 16i$$

$$z_1 = \frac{2i + 6 - \sqrt{16i - 12}}{2i}$$
$$z_2 = \frac{2i + 6 + \sqrt{16i - 12}}{2i}$$


**Не решил, не понимаю как найти корень из -12 + 16i. И я должен получить 2 корня. Т.е. в конечном итоге должен получить 4 корня квадратного уравнения.**

$\sqrt[n]{z} =  \sqrt[n]{|z|}\Big(cos{\frac{ϕ + 2 \pi k}{n}} +i\sin{\frac{ϕ+2\pi k}{n}}\Big)$

$$|z| = \sqrt{(-12)^2 + 16^2} = 20$$

$$\phi = \pi + arctg(-\frac{16}{12})$$

$$z = 20\Big(\cos \Big(\pi -arctg\Big(\frac{4}{3}\Big)\Big) +i\sin\Big(\pi -arctg\Big(\frac{4}{3}\Big) \Big) \Big)$$

$\sqrt{-12+16i} =\sqrt{20\Big(\cos \Big(\pi -arctg\Big(\frac{4}{3}\Big)\Big) +i\sin\Big(\pi -arctg\Big(\frac{4}{3}\Big) \Big) \Big)} = \sqrt{20}\Big(cos{\frac{\pi -arctg\Big(\frac{4}{3}\Big) + 2 \pi k}{2}} +i\sin{\frac{\pi -arctg\Big(\frac{4}{3}\Big)+2\pi k}{2}}\Big)$

$k = 0$

$2\sqrt{5}\Big(cos{\frac{\pi -arctg\Big(\frac{4}{3}\Big)}{2}} +i\sin{\frac{\pi -arctg\Big(\frac{4}{3}\Big)}{2}}\Big)$

$k = 1$

$2\sqrt{5}\Big(cos{\frac{3\pi -arctg\Big(\frac{4}{3}\Big)}{2}} +i\sin{\frac{3\pi -arctg\Big(\frac{4}{3}\Big)}{2}}\Big)$

$(2+4i)(2+4i) = 4 + 8i +8i +16i^2 = 4+16i-16 = -12+16i$
$(-2-4i)(-2-4i) = 4 + 8i +8i +16i^2 = 4+16i-16 = -12+16i$

In [11]:
a = (0 + 1j)
b = (-6 - 2j)
c = (2 - 11j)

D = b**2 - 4 * a * c
D

(-12+16j)

In [12]:
z1 = (-b + D**(1/2)) / 2*a
z1

(-3+4j)

In [13]:
z2 = (-b - D**(1/2)) / 2*a
z2

(1+1.9999999999999998j)

# 7

Вычислите

$$\Big(\frac{1}{2}+\frac{\sqrt{3}}{2}i\Big)^{20}$$


$$|z|=\sqrt{\frac{1}{4} +\frac{3}{4}}= 1$$


$$Re(z) = \frac{1}{2} > 0, Im(z)=\frac{\sqrt{3}}{2} > 0$$

$$\phi = arctg(z) = arctg\Big(\frac{2\sqrt{3}}{2}\Big) = \frac{\pi}{3}$$

$$z = \cos\Big(\frac{\pi}{3}\Big) +  i\sin\Big(\frac{\pi}{3}\Big)$$

$z^n =  |z|^n\Big(cos(nϕ) +i\sin(nϕ)\Big)$

$\Big(\frac{1}{2}+\frac{\sqrt{3}}{2}i\Big)^{20} = cos(20\frac{\pi}{3}) +i\sin(20\frac{\pi}{3}) = cos(\frac{2\pi}{3}) +i\sin(\frac{2\pi}{3})$

# 8





##а)
  Пусть $V = M_2(ℜ)$, $U =\Big\{ \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}  \Big | a + d = 0 \Big \}$. Покажите, что U – подпространство V . Иными словами, нужно показать, что множество 2 × 2 матриц с нулевым следом является подпространством пространства всех вещественных 2 × 2 матриц (следом матрицы называется сумма элементов главной диагонали матрицы). Найдите размерность U и предъявите некоторый базис U.


Если верно понимаю, то нам нужно рассмотреть сложение двух матриц со следом ноль и умножение матрицы на константу.

$$\begin{pmatrix}
a_1 & b_1 \\
c_1 & d_1
\end{pmatrix}+\begin{pmatrix}
a_2 & b_2 \\
c_2 & d_2
\end{pmatrix} = \begin{pmatrix}
a_1 + a_2 & b_1 + b_2 \\
c_1 + c_2 & d_1 + d_2
\end{pmatrix}$$

по условию $a_1 + d_1 = 0$ и $a_2 + d_2 = 0$
$$a_1 + a_2 + d_1 + d_2 = a_1 + d_1 + a_2 + d_2 = 0$$

$$λ\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}$$

$$λa + λd = λ(a + d)$$

Т.е. да, у мы не вышли из нашего подпространства.

Честно говоря, плохо понял эту тему. Особенно размерность. В данном случае, зацепился за степень свободы. Т.е., если бы все элементы в нашей матрице были бы независимы, то размерность была бы 4. Но у нас один элемент определённо задан другим элементом. Таким образом размерность = 3.

Т.е. нам нужно 3 вектора, которые зададут нам базис.

Но как размерность и ранг в данном случае связаны - до конца не понимаю.

Для задания элемента справа сверху
$$
e_1 = \begin{pmatrix}
0 & 1\\
0 & 0
\end{pmatrix}$$

Для задания элемента слева снизу
$$
e_2 = \begin{pmatrix}
0 & 0\\
1 & 0
\end{pmatrix}$$

Для задания элементов по диагонали

$$
e_3 = \begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix}$$


##б)
В выбранном базисе найдите координаты матрицы

$$
\begin{pmatrix}
-1 & 2\\
3 & 1
\end{pmatrix}$$
(то есть укажите, как эта матрица выражается через базисные.)


$$
3\begin{pmatrix}
0 & 0\\
1 & 0
\end{pmatrix} + 2\begin{pmatrix}
0 & 1\\
0 & 0
\end{pmatrix} -1\begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix}$$

# 9

Найдите все значения λ ∈ ℜ, при которых вектор v линейно выражается через векторы a1, a2, a3, где

$$a_1 = \begin{pmatrix}
2\\
3\\
5
\end{pmatrix}
a_2 = \begin{pmatrix}
3\\
7\\
8
\end{pmatrix}
a_3 = \begin{pmatrix}
1\\
-6\\
1
\end{pmatrix}
v = \begin{pmatrix}
7\\
-2\\
λ
\end{pmatrix}$$

$$\forall λ$$

Может быть неверно понял, но у нас размерность пространства 3. И 3 линейно независимых вектора уже будут давать базис.

# 10

Найдите какой-нибудь базис системы векторов и выразите через него все остальные векторы системы:

$a1 = (2,−1, 3, 5), a2 = (4,−3, 1, 3), a3 = (3,−2, 3, 4), a4 = (4,−1, 15, 17), a5 = (7,−6,−7, 0).$

Для нахождения базиса достаточно выделить максимальную линейно независимую подсистему из системы векторов $\{a1, . . . , a5\}$.

Составим линейную комбинацию:

$$w_1a_1 + w_2a_2 + w_3a_3 + w_4a_4 + w_5a_5$$

$$(2w_1 + 4w_2 + 3w_3 + 4w_4 + 7w_5,  - w_1 -3w_2 - 2w_3 - w_4 - 6w_5, 3w_1 + w_2 + 3w_3 + 15w_4 - 7w_5, 5w_1 + 3w_2 + 4w_3 + 17w_4 + 0w_5) = (0, 0, 0, 0)$$

$$\begin{cases}
2w_1 + 4w_2 + 3w_3 + 4w_4 + 7w_5 = 0\\
-w_1 -3w_2 - 2w_3 - w_4 - 6w_5 = 0\\
3w_1 + w_2 + 3w_3 + 15w_4 - 7w_5 = 0\\
5w_1 + 3w_2 + 4w_3 + 17w_4 + 0w_5 = 0
\end{cases}$$



$$\begin{pmatrix}
2 & 4 & 3 & 4 & 7 \\
-1 & -3 & -2 & -1 & -6\\
3 & 1 & 3 & 15 & -7\\
5 & 3 & 4 & 17 & 0
\end{pmatrix}→\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
2 & 4 & 3 & 4 & 7 \\
3 & 1 & 3 & 15 & -7\\
5 & 3 & 4 & 17 & 0
\end{pmatrix}→
\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
0 & -2 & -1 & 2 & -5 \\
0 & -8 & -3 & 12 & -25\\
0 & -12 & -6 & 12 & -30
\end{pmatrix}→
\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
0 & -2 & -1 & 2 & -5 \\
0 & -8 & -3 & 12 & -25\\
0 & 0 & 0 & 0 & 0
\end{pmatrix}→
\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
0 & -2 & -1 & 2 & -5 \\
0 & -8 & -3 & 12 & -25
\end{pmatrix}→
\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
0 & 2 & 1 & -2 & 5 \\
0 & -8 & -3 & 12 & -25
\end{pmatrix}→
\begin{pmatrix}
1 & 3 & 2 & 1 & 6\\
0 & 2 & 1 & -2 & 5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 1 & 1 & 3 & 1\\
0 & 2 & 1 & -2 & 5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 1 & 1 & 3 & 1\\
0 & 1 & 0.5 & -1 & 2.5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 1 & 0 & -1 & 6\\
0 & 1 & 0.5 & -1 & 2.5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 0 & -0.5 & 0 & 3.5\\
0 & 1 & 0.5 & -1 & 2.5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 0 & -0.5 & 0 & 3.5\\
0 & 1 & 0 & -3 & 5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}→
\begin{pmatrix}
1 & 0 & 0 & 2 & 1\\
0 & 1 & 0 & -3 & 5 \\
0 & 0 & 1 & 4 & -5
\end{pmatrix}$$


$w_1, w_2, w_3$ - являются главными компонентами, $w_4, w_5$ - свободные.

Т.е. вектора $a4, a5$ - можно представить в виде линейной комбинации других векторов.

Честно говоря, не очень пока понял, возможно просто повезло. Т.е. на бумаге я просто составил СЛУ через черту и посчитал.

$$a4 = 2a1 - 3a2 + 4a3$$
$$a5 = a1 + 5a2 -5a3$$



In [14]:
a1 = np.array([2, -1, 3, 5])
a2 = np.array([4, -3, 1, 3])
a3 = np.array([3, -2, 3, 4])

In [15]:
2 * a1 - 3 *a2 + 4 * a3

array([ 4, -1, 15, 17])

In [16]:
a1 + 5 * a2 - 5 * a3

array([ 7, -6, -7,  0])

In [17]:
A = np.array([[2, 4, 3, 4, 7], [-1, -3, -2, -1, -6], [3, 1, 3, 15, -7], [5, 3, 4, 17, 0]])
la.matrix_rank(A)

3

# 11

Для каждого значения λ ∈ ℜ найдите ранг матрицы

$$\begin{pmatrix}
-λ & 1 & 2 & 3 & 1 \\
1 & -λ & 3 & 2 & 1\\
2 & 3 & -λ & 1 & 1\\
3 & 2 & 1 & -λ & 1
\end{pmatrix}$$

**Не решил. Если честно, не понимаю куда двигаться. Т.е. я вроде и окаймляющих миноров пробовал и вот ниже привёл пример начала для метода элементарных преобразований**

$$\begin{pmatrix}
-λ & 1 & 2 & 3 & 1 \\
1 & -λ & 3 & 2 & 1\\
2 & 3 & -λ & 1 & 1\\
3 & 2 & 1 & -λ & 1
\end{pmatrix}→
\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
2 & 3 & -λ & 1 & 1\\
3 & 2 & 1 & -λ & 1\\
-λ & 1 & 2 & 3 & 1
\end{pmatrix}→
\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 3+2λ & -λ-6 & -3 & -1\\
0 & 2-3λ & -8 & -λ-6 & -2\\
0 & 1-λ^2 & 2+3λ & 3+2λ & 1+λ
\end{pmatrix}→$$

$$λ \neq 0$$

$$→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 2-3λ & -8 & -λ-6 & -2\\
0 & 1-λ^2 & 2+3λ & 3+2λ & 1+λ
\end{pmatrix}→$$

$$λ \neq -\frac{3}{2}$$

$$→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 2-3λ & -8 & -λ-6 & -2\\
0 & 1-λ^2 & 2+3λ & 3+2λ & 1+λ
\end{pmatrix}→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 0 & \frac{-3λ^2 - 32 - 12}{2λ + 3}& \frac{-2λ^2 - 33λ - 12}{2λ + 3}& \frac{-7λ - 4}{2λ + 3}\\
0 & 1-λ^2 & 2+3λ & 3+2λ & 1+λ
\end{pmatrix}→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 0 & \frac{-3λ^2 - 32 - 12}{2λ + 3}& \frac{-2λ^2 - 33λ - 12}{2λ + 3}& \frac{-7λ - 4}{2λ + 3}\\
0 & 0 & \frac{-3λ^3 + 14λ + 12}{2λ + 3} & \frac{λ^2 + 12λ + 12}{2λ + 3} & \frac{λ^2 + 5λ  + 4}{2λ + 3}
\end{pmatrix}→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 0 & -3λ^2 - 32 - 12& -2λ^2 - 33λ - 12& -7λ - 4\\
0 & 0 & -3λ^3 + 14λ + 12 & λ^2 + 12λ + 12 & λ^2 + 5λ  + 4
\end{pmatrix}→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 0 & 1 & \frac{-2λ^2 - 33λ - 12}{-3λ^2 - 32 - 12}& \frac{-7λ - 4}{-3λ^2 - 32 - 12}\\
0 & 0 & -3λ^3 + 14λ + 12 & λ^2 + 12λ + 12 & λ^2 + 5λ  + 4
\end{pmatrix}$$

$$-3λ^2 - 32 - 12 \neq 0$$


$$→\begin{pmatrix}
1 & -λ & 3 & 2 & 1\\
0 & 1 & \frac{-λ-6}{2λ+3} & \frac{-3}{2λ+3} & \frac{-1}{2λ+3}\\
0 & 0 & 1 & \frac{-2λ^2 - 33λ - 12}{-3λ^2 - 32 - 12}& \frac{-7λ - 4}{-3λ^2 - 32 - 12}\\
0 & 0 & 0 & (λ^2 + 12λ + 12) - \frac{(-2λ^2 - 33λ - 12)(-3λ^3 + 14λ + 12)}{-3λ^2 - 32 - 12} & (λ^2 + 5λ  + 4) - \frac{(-7λ - 4)(-3λ^3 + 14λ + 12)}{-3λ^2 - 32 - 12}
\end{pmatrix}$$



Где-то здесь остановлюсь. Возможно я просто наделал кучу ошибок, а оно должно было где-то хорошо сократиться. Но вероятно я просто даже не близко пошёл к нужному решению.
В теории, в этом решении надо искать корни и проверять для каждого λ.

# 12
Известно, что присоединенная к A матрица (то есть транспонированная матрица алгебраических дополнений) равна

$$\hat{A} = \begin{pmatrix}
1 & -2 & 1 \\
3 & -4 & 3 \\
-9 & 10 & -7
\end{pmatrix}$$

Чему может равняться матрица A? (указание: присоединенная матрица имеет отношение к явной формуле для обратной матрицы — подумайте, как ее можно применить здесь)

**Не решил. Подогнал под требуемый результат.**

$$A^{-1} = \frac{\hat{A}}{|A|}$$
$$I= \frac{A\hat{A}}{|A|}$$
$$|A|I= A\hat{A}$$
$$A = |A|\hat{A}^{-1}$$

Видимо предполагаем, что $|A| \neq 0$

$$\hat{A}^{-1} = \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 1  \\
3 & -4 & 3 \\
-9 & 10 & -7
\end{matrix}\right|
\begin{matrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 1  \\
0 & 2 & 0 \\
0 & -8 & 2
\end{matrix}\right|
\begin{matrix}
1 & 0 & 0\\
-3 & 1 & 0\\
9 & 0 & 1
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 1  \\
0 & 1 & 0 \\
0 & -8 & 2
\end{matrix}\right|
\begin{matrix}
1 & 0 & 0\\
-1.5 & 0.5 & 0\\
9 & 0 & 1
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 1  \\
0 & 1 & 0 \\
0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
1 & 0 & 0\\
-1.5 & 0.5 & 0\\
-3 & 4 & 1
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 1  \\
0 & 1 & 0 \\
0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
1 & 0 & 0\\
-1.5 & 0.5 & 0\\
-1.5 & 2 & 0.5
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 0  \\
0 & 1 & 0 \\
0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
2.5 & -2 & -0.5\\
-1.5 & 0.5 & 0\\
-1.5 & 2 & 0.5
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0  \\
0 & 1 & 0 \\
0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
-0.5 & -1 & -0.5\\
-1.5 & 0.5 & 0\\
-1.5 & 2 & 0.5
\end{matrix}
\end{pmatrix} = \begin{pmatrix}
-0.5 & -1 & -0.5\\
-1.5 & 0.5 & 0\\
-1.5 & 2 & 0.5
\end{pmatrix}$$

Если честно, то тут я смухлевал. Не очень я понял как находить детерминант A. Но тут матрицу, которую нужно получить начинается с 1. А потому нам нужно умножить на 2. Т.е. определитель A должен быть равен 2. И мы знаем, что определитель присоединённой матрицы равен 4. Тогда мы получаем, что $|A| = \sqrt{|\hat{A}|}$

$$|\hat{A}^{-1}| =\begin{vmatrix}
1 & -2 & 1\\
3 & -4 & 3\\
-9 & 10 & -7
\end{vmatrix} = 28 + 54 + 30 - 36 - 30 - 42 = 4$$

$$|A| = 2$$

$$A = 2\begin{pmatrix}
-0.5 & -1 & -0.5\\
-1.5 & 0.5 & 0\\
-1.5 & 2 & 0.5
\end{pmatrix} = \begin{pmatrix}
-1 & -2 & -1\\
-3 & 1 & 0\\
-3 & 4 & 1
\end{pmatrix}$$

Ничего более умного, чем взять определитель от обеих частей уравнения - не придумал. Можно так делать - не уверен.

$$|A|I= A\hat{A}$$

$$det(|A|I)= det(A\hat{A}) = det(A)det(\hat{A})$$
$$det(|A|I) = det(A)det(\hat{A})$$
Т.е. у нас число умножить на единичную матрицу 3 на 3.
$$|A|^3det(I)= det(A)det(\hat{A})$$
$$\frac{|A|^3}{|A|}= det(\hat{A})$$
$$|A|^2= det(\hat{A})$$
$$|A|^2= det(\hat{A})$$
$$|A|= \sqrt{det(\hat{A})}$$

Не знаю, я не придумал как по-другому получить корень из определителя. В чистом виде, подгонка.